{:edges_1=>
  {:should_include=>"true",
   :description=>nil,
   :help=>nil,
   :code_name=>:edges_1,
   :must_pass=>
    [{:test=>"kind_of? Numeric",
      :explanation=>
       "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
   :type=>:Float},
 :edges_2=>
  {:should_include=>"true",
   :description=>nil,
   :help=>nil,
   :code_name=>:edges_2,
   :must_pass=>
    [{:test=>"kind_of? Numeric",
      :explanation=>
       "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
   :type=>:Float},
 :edges_3=>
  {:should_include=>"true",
   :description=>nil,
   :help=>nil,
   :code_name=>:edges_3,
   :must_pass=>
    [{:test=>"kind_of? Numeric",
      :explanation=>
       "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
   :type=>:Float},
 :beta=>
  {:should_include=>"true",
   :description=>nil,
   :help=>nil,
   :code_name=>:beta,
   :must_pass=>
    [{:test=>"kind_of? Numeric",
      :explanation=>
       "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
   :type=>:Float},
 :zeff=>
  {:should_include=>"true",
   :description=>nil,
   :help=>nil,
   :code_name=>:zeff,
   :must_pass=>
    [{:test=>"kind_of? Numeric",
      :explanation=>
       "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
   :type=>:Float},
 :grid_option=>
  {:should_include=>"true",
   :description=>nil,
   :help=>nil,
   :code_name=>:grid_option,
   :must_pass=>
    [{:test=>"kind_of? String",
      :explanation=>"This variable must be a string."}],
   :type=>:String},
 :aky=>
  {:should_include=>"true",
   :description=>nil,
   :help=>nil,
   :code_name=>:aky,
   :must_pass=>
    [{:test=>"kind_of? Numeric",
      :explanation=>
       "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
   :type=>:Float},
 :akx=>
  {:should_include=>"true",
   :description=>nil,
   :help=>nil,
   :code_name=>:akx,
   :must_pass=>
    [{:test=>"kind_of? Numeric",
      :explanation=>
       "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
   :type=>:Float},
 :ntheta=>
  {:should_include=>"true",
   :description=>nil,
   :help=>nil,
   :code_name=>:ntheta,
   :must_pass=>
    [{:test=>"kind_of? Integer",
      :explanation=>"This variable must be an integer."}],
   :type=>:Integer},
 :nperiod=>
  {:should_include=>"true",
   :description=>nil,
   :help=>nil,
   :code_name=>:nperiod,
   :must_pass=>
    [{:test=>"kind_of? Integer",
      :explanation=>"This variable must be an integer."}],
   :type=>:Integer},
 :eps=>
  {:should_include=>"true",
   :description=>nil,
   :help=>nil,
   :code_name=>:eps,
   :must_pass=>
    [{:test=>"kind_of? Numeric",
      :explanation=>
       "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
   :type=>:Float},
 :epsl=>
  {:should_include=>"true",
   :description=>nil,
   :help=>nil,
   :code_name=>:epsl,
   :must_pass=>
    [{:test=>"kind_of? Numeric",
      :explanation=>
       "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
   :type=>:Float},
 :shat=>
  {:should_include=>"true",
   :description=>nil,
   :help=>nil,
   :code_name=>:shat,
   :must_pass=>
    [{:test=>"kind_of? Numeric",
      :explanation=>
       "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
   :type=>:Float},
 :pk=>
  {:should_include=>"true",
   :description=>nil,
   :help=>nil,
   :code_name=>:pk,
   :must_pass=>
    [{:test=>"kind_of? Numeric",
      :explanation=>
       "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
   :type=>:Float},
 :shift=>
  {:should_include=>"true",
   :description=>nil,
   :help=>nil,
   :code_name=>:shift,
   :must_pass=>
    [{:test=>"kind_of? Numeric",
      :explanation=>
       "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
   :type=>:Float},
 :equilibrium_option=>
  {:should_include=>"true",
   :description=>nil,
   :help=>nil,
   :code_name=>:equilibrium_option,
   :must_pass=>
    [{:test=>"kind_of? String",
      :explanation=>"This variable must be a string."}],
   :type=>:String},
 :model_option=>
  {:should_include=>"true",
   :description=>nil,
   :help=>nil,
   :code_name=>:model_option,
   :must_pass=>
    [{:test=>"kind_of? String",
      :explanation=>"This variable must be a string."}],
   :type=>:String},
 :ngauss=>
  {:should_include=>"true",
   :description=>nil,
   :help=>nil,
   :code_name=>:ngauss,
   :must_pass=>
    [{:test=>"kind_of? Integer",
      :explanation=>"This variable must be an integer."}],
   :type=>:Integer},
 :negrid=>
  {:should_include=>"true",
   :description=>nil,
   :help=>nil,
   :code_name=>:negrid,
   :must_pass=>
    [{:test=>"kind_of? Integer",
      :explanation=>"This variable must be an integer."}],
   :type=>:Integer},
 :gridfac=>
  {:should_include=>"true",
   :description=>nil,
   :help=>nil,
   :code_name=>:gridfac,
   :must_pass=>
    [{:test=>"kind_of? Numeric",
      :explanation=>
       "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
   :type=>:Float},
 :omprimfac=>
  {:should_include=>"true",
   :description=>nil,
   :help=>nil,
   :code_name=>:omprimfac,
   :must_pass=>
    [{:test=>"kind_of? Numeric",
      :explanation=>
       "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
   :type=>:Float},
 :boundary_option=>
  {:should_include=>"true",
   :description=>nil,
   :help=>nil,
   :code_name=>:boundary_option,
   :must_pass=>
    [{:test=>"kind_of? String",
      :explanation=>"This variable must be a string."}],
   :type=>:String},
 :adiabatic_option=>
  {:should_include=>"true",
   :description=>nil,
   :help=>nil,
   :code_name=>:adiabatic_option,
   :must_pass=>
    [{:test=>"kind_of? String",
      :explanation=>"This variable must be a string."}],
   :type=>:String},
 :g_exb=>
  {:should_include=>"true",
   :description=>nil,
   :help=>nil,
   :code_name=>:g_exb,
   :must_pass=>
    [{:test=>"kind_of? Numeric",
      :explanation=>
       "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
   :type=>:Float},
 :nonad_zero=>
  {:should_include=>"true",
   :description=>nil,
   :help=>nil,
   :code_name=>:nonad_zero,
   :must_pass=>
    [{:test=>"kind_of? String and FORTRAN_BOOLS.include? self",
      :explanation=>
       "This variable must be a fortran boolean. (In Ruby this is represented as a string: e.g. '.true.')"}],
   :type=>:Fortran_Bool},
 :field_option=>
  {:should_include=>"true",
   :description=>nil,
   :help=>nil,
   :code_name=>:field_option,
   :must_pass=>
    [{:test=>"kind_of? String",
      :explanation=>"This variable must be a string."}],
   :type=>:String},
 :wstar_units=>
  {:should_include=>"true",
   :description=>nil,
   :help=>nil,
   :code_name=>:wstar_units,
   :must_pass=>
    [{:test=>"kind_of? String and FORTRAN_BOOLS.include? self",
      :explanation=>
       "This variable must be a fortran boolean. (In Ruby this is represented as a string: e.g. '.true.')"}],
   :type=>:Fortran_Bool},
 :fphi=>
  {:should_include=>"true",
   :description=>nil,
   :help=>nil,
   :code_name=>:fphi,
   :must_pass=>
    [{:test=>"kind_of? Numeric",
      :explanation=>
       "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
   :type=>:Float},
 :fapar=>
  {:should_include=>"true",
   :description=>nil,
   :help=>nil,
   :code_name=>:fapar,
   :must_pass=>
    [{:test=>"kind_of? Numeric",
      :explanation=>
       "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
   :type=>:Float},
 :faperp=>
  {:should_include=>"true",
   :description=>nil,
   :help=>nil,
   :code_name=>:faperp,
   :must_pass=>
    [{:test=>"kind_of? Numeric",
      :explanation=>
       "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
   :type=>:Float},
 :delt=>
  {:should_include=>"true",
   :description=>nil,
   :help=>nil,
   :code_name=>:delt,
   :must_pass=>
    [{:test=>"kind_of? Numeric",
      :explanation=>
       "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
   :type=>:Float},
 :nstep=>
  {:should_include=>"true",
   :description=>nil,
   :help=>nil,
   :code_name=>:nstep,
   :must_pass=>
    [{:test=>"kind_of? Integer",
      :explanation=>"This variable must be an integer."}],
   :type=>:Integer},
 :delt_adj=>
  {:should_include=>"true",
   :description=>nil,
   :help=>nil,
   :code_name=>:delt_adj,
   :must_pass=>
    [{:test=>"kind_of? Numeric",
      :explanation=>
       "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
   :type=>:Float},
 :delt_minimum=>
  {:should_include=>"true",
   :description=>nil,
   :help=>nil,
   :code_name=>:delt_minimum,
   :must_pass=>
    [{:test=>"kind_of? Numeric",
      :explanation=>
       "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
   :type=>:Float},
 :layout=>
  {:should_include=>"true",
   :description=>nil,
   :help=>nil,
   :code_name=>:layout,
   :must_pass=>
    [{:test=>"kind_of? String",
      :explanation=>"This variable must be a string."}],
   :type=>:String},
 :collision_model=>
  {:should_include=>"true",
   :description=>nil,
   :help=>nil,
   :code_name=>:collision_model,
   :must_pass=>
    [{:test=>"kind_of? String",
      :explanation=>"This variable must be a string."}],
   :type=>:String},
 :nonlinear_mode=>
  {:should_include=>"true",
   :description=>nil,
   :help=>nil,
   :code_name=>:nonlinear_mode,
   :must_pass=>
    [{:test=>"kind_of? String",
      :explanation=>"This variable must be a string."}],
   :type=>:String},
 :flow_mode=>
  {:should_include=>"true",
   :description=>nil,
   :help=>nil,
   :code_name=>:flow_mode,
   :must_pass=>
    [{:test=>"kind_of? String",
      :explanation=>"This variable must be a string."}],
   :type=>:String},
 :cfl=>
  {:should_include=>"true",
   :description=>nil,
   :help=>nil,
   :code_name=>:cfl,
   :must_pass=>
    [{:test=>"kind_of? Numeric",
      :explanation=>
       "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
   :type=>:Float},
 :nspec=>
  {:should_include=>"true",
   :description=>nil,
   :help=>nil,
   :code_name=>:nspec,
   :must_pass=>
    [{:test=>"kind_of? Integer",
      :explanation=>"This variable must be an integer."}],
   :type=>:Integer},
 :dummy_for_arrays=>
  {:should_include=>"true",
   :description=>"",
   :help=>"Tests whether the routines for writing arrays work",
   :code_name=>:dummy_for_arrays,
   :must_pass=>
    [{:test=>"kind_of? Numeric",
      :explanation=>
       "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
   :type=>:Float,
   :autoscanned_defaults=>[]}}
