{:cubecalc=>
  {:description=>"",
   :should_include=>"true",
   :variables=>
    {:calculate_sides=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:calculate_sides,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer,
       :autoscanned_defaults=>[0]},
     :must_sleep=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:must_sleep,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer,
       :autoscanned_defaults=>[0]},
     :width=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:width,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float,
       :autoscanned_defaults=>[1.0]},
     :depth=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:depth,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float,
       :autoscanned_defaults=>[1.0]},
     :height=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:height,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float,
       :autoscanned_defaults=>[1.0]}}}}
